site_name: "Brive Docs"

theme: windmill 

docs_dir: src
site_dir: docs

extra:
  logo: "img/icon.png"
  version: v4

static_resources:
  - include: 
    - images/*.png
    - images/*.jpg
  - exclude:
    - _*

plugins:
  - markdownmermaid:
      init_options: 
          - startOnLoad: true
          - theme: "forest" 
          - flowchart:
              - curve: "cardinal"
              - useMaxWidth: true

extra_javascript:
  - https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js 

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - attr_list  